# Assignment 7: Reinforcement Learning

- Name: Gyanas Luitel
- Roll No: 27
- Group: Computer Science

## Creating an environment

In [2]:
import argparse

In [3]:
import gym

In [4]:
# Function to parse the input arguments
def build_arg_parser():
    parser = argparse.ArgumentParser(description='Run an environment')
    parser.add_argument('--input-env', dest='input_env', required=True,
                       choices=['cartpole', 'mountaincar', 'pendulum', 'taxi',
                               'lake'],
                       help='Specify the name of the environment')
    return parser

In [5]:
def environment_main(input_env):
    input_env = input_env
    
    name_map = {'cartpole': 'CartPole-v0',
               'mountaincar': 'MountainCar-v0',
               'pendulum': 'Pendulum-v0',
               'taxi': 'Taxi-v1',
               'lake': 'FrozenLake-v0'}
    
    # Create the environment and reset it
    env = gym.make(name_map[input_env])
    env.reset()
    
    # Iterate 1000 times
    for _ in range(1000):
        # Render the environment
        env.render()
        
        # take a random action
        env.step(env.action_space.sample())
    env.close()

In [6]:
environment_main('cartpole')

C:\Users\gluit\anaconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [7]:
environment_main('mountaincar')

## Building a learning agent

In [8]:
def build_arg_parser():
    parser = argparse.ArgumentParser(description='Run an environment')
    parser.add_argument('--input-env', dest='input_env', required=True,
                       choices=['cartpole', 'mountaincar', 'pendulum'],
                       help='Specify the name of the environment')
    return parser

In [9]:
def balancer_main(input_env):
    input_env = input_env
    
    name_map = {'cartpole': 'CartPole-v0',
               'mountaincar': 'MountainCar-v0',
               'pendulum': 'Pendulum-v0'}
    
    # Create the environment
    env = gym.make(name_map[input_env])
    
    # Start iterating
    for _ in range(20):
        # Reset the environment
        observation = env.reset()
        
        # Iterate 100 times
        for i in range(100):
            # Render the environment
            env.render()
            
            # Print the current observation
            print(observation)
            
            # Take action
            action = env.action_space.sample()
            
            # Extract the observation, reward, status and other infor based on the action taken
            observation, reward, done, info = env.step(action)
            
            # Check if it's done
            if done:
                print('Episode finished after {} timesteps'.format(i+1))
                break
            
    env.close()

In [10]:
balancer_main('cartpole')

[ 0.0250858  -0.04393747 -0.0079986  -0.02020624]
[ 0.02420705 -0.23894381 -0.00840273  0.26994234]
[ 0.01942818 -0.43394484 -0.00300388  0.5599632 ]
[ 0.01074928 -0.23878086  0.00819538  0.26633541]
[ 0.00597366 -0.43401881  0.01352209  0.56159192]
[-0.00270672 -0.6293279   0.02475393  0.85850413]
[-0.01529327 -0.43455174  0.04192401  0.57370632]
[-0.02398431 -0.24004188  0.05339814  0.29451995]
[-0.02878515 -0.43588284  0.05928854  0.60355428]
[-0.0375028  -0.24163803  0.07135962  0.33011962]
[-0.04233556 -0.04760061  0.07796202  0.06076616]
[-0.04328758  0.14632199  0.07917734 -0.20633656]
[-0.04036114  0.34022769  0.07505061 -0.47303005]
[-0.03355658  0.14413048  0.06559001 -0.15766807]
[-0.03067397  0.33825504  0.06243665 -0.42895915]
[-0.02390887  0.142307    0.05385746 -0.11726536]
[-0.02106273 -0.05354361  0.05151216  0.19191102]
[-0.0221336   0.14080504  0.05535038 -0.08408738]
[-0.0193175  -0.05506485  0.05366863  0.22553222]
[-0.0204188   0.13925064  0.05817927 -0.04975035]


[ 0.02975376  0.57380191 -0.05955781 -0.88352668]
[ 0.0412298   0.76967988 -0.07722834 -1.19432233]
[ 0.05662339  0.57563824 -0.10111479 -0.92681   ]
[ 0.06813616  0.38201633 -0.11965099 -0.6675377 ]
[ 0.07577648  0.18874362 -0.13300174 -0.4147949 ]
[ 0.07955136 -0.00426721 -0.14129764 -0.1668229 ]
[ 0.07946601 -0.19711359 -0.1446341   0.07816041]
[ 0.07552374 -0.3898979  -0.14307089  0.32194318]
[ 0.06772578 -0.19305922 -0.13663203 -0.01221763]
[ 0.0638646   0.00373078 -0.13687638 -0.34469655]
[ 0.06393921 -0.18920557 -0.14377031 -0.09811494]
[ 0.0601551   0.00765293 -0.14573261 -0.43247917]
[ 0.06030816 -0.18513749 -0.15438219 -0.18905286]
[ 0.05660541  0.0118174  -0.15816325 -0.52617981]
[ 0.05684176 -0.18076686 -0.16868685 -0.28721547]
[ 0.05322642  0.01630871 -0.17443116 -0.62799198]
[ 0.0535526   0.21338074 -0.186991   -0.9701374 ]
[ 0.05782021  0.41045329 -0.20639375 -1.31524872]
Episode finished after 27 timesteps
[ 0.0067558  -0.03605331 -0.02167156 -0.04777118]
[ 0.00603473 -

[-0.06474962 -0.3484162   0.0330865   0.12462131]
[-0.07171794 -0.54399615  0.03557893  0.42755633]
[-0.08259787 -0.34939569  0.04413006  0.14629838]
[-0.08958578 -0.15493258  0.04705603 -0.13214228]
[-0.09268443 -0.35069589  0.04441318  0.17500701]
[-0.09969835 -0.5464244   0.04791332  0.48136344]
[-0.11062684 -0.74218876  0.05754059  0.78875412]
[-0.12547061 -0.93805181  0.07331567  1.09897005]
[-0.14423165 -1.13405819  0.09529507  1.4137253 ]
[-0.16691281 -0.94023751  0.12356958  1.15228774]
[-0.18571756 -0.74692497  0.14661533  0.90076701]
[-0.20065606 -0.94369666  0.16463067  1.23570852]
[-0.21953    -0.75102783  0.18934484  0.99879597]
[-0.23455055 -0.9481068   0.20932076  1.34446641]
Episode finished after 46 timesteps
[-0.01918996 -0.02739434 -0.04372641 -0.01269096]
[-0.01973785 -0.2218628  -0.04398023  0.26588145]
[-0.02417511 -0.02614164 -0.0386626  -0.04034243]
[-0.02469794 -0.22068846 -0.03946945  0.23989575]
[-0.02911171 -0.02502555 -0.03467153 -0.06497104]
[-0.02961222 -

## Example code for q-learning - Mastering Machine Learning with Python in Six Steps

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from random import randint

In [19]:
# defines the reward/link connection graph
R = np.matrix([[-1, -1, -1, -1, 0, -1],
              [-1, -1, -1, 0, -1, 100],
              [-1, -1, -1, 0, -1, -1],
              [-1, 0, 0, -1, 0, -1],
              [0, -1, -1, 0, -1, 100],
              [-1, 0, -1, -1, 0, 100]]).astype("float32")

Q = np.zeros_like(R)

In [20]:
# learning parameter
gamma = 0.8

# Initialization random_state
initial_state = randint(0, 4)

# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

# This function chooses at random which action to be performed within the range of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act, 1))
    return next_action

# This function updates the Q matrix according to the path selected and the Q learning algorithm
def update(current_state, action, gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
    
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]
    
    # Q learning formula
    Q[current_state, action] = R[current_state, action] + gamma * max_value

# Get available actions in the current state
available_act = available_actions(initial_state)

# Sample next action to be performed
action = sample_next_action(available_act)

# Train over 100 iterations, re-iterate the process above.
for i in range(100):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state, action, gamma)

# Normalize the "trained" Q matrix
print("Trained Q matrix: \n", Q/np.max(Q)*100)

Trained Q matrix: 
 [[  0.           0.           0.           0.          68.41573715
    0.        ]
 [  0.           0.           0.          54.73259091   0.
   98.71386886]
 [  0.           0.           0.          54.73259091   0.
    0.        ]
 [  0.          68.41573715  43.78607273   0.          68.41573715
    0.        ]
 [ 54.73259091   0.           0.          54.73259091   0.
   85.5196774 ]
 [  0.          68.41573715   0.           0.          68.41573715
  100.        ]]


In [21]:
# Testing
current_state = 2
steps = [current_state]

while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size = 1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index

# Print selected sequence of steps
print("Best sequence path: ", steps)

Best sequence path:  [2, 3, 1, 5]
